[general]
STREAMLIT_ENV = "cloud"

[sendgrid]
SENDGRID_API_KEY = "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"
SENDER_EMAIL = "hemalathadonapati.ai@gmail.com"

[together]
TOGETHER_API_KEY = "3e9b9ae69cc3a851a97de192e4b0ec7236e2cfabfc922335bbf86677fd5f9e05"


[openai]
OPENAI_API_KEY = "dummy_value_to_satisfy_openai_dependency"

[firebase]
FIREBASE_CREDENTIALS_JSON = "..."
