

[sendgrid]
SENDGRID_API_KEY = "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"
SENDER_EMAIL = "hemalathadonapati.ai@gmail.com"

[together]
TOGETHER_API_KEY = "3e9b9ae69cc3a851a97de192e4b0ec7236e2cfabfc922335bbf86677fd5f9e05"


[openai]
OPENAI_API_KEY = "dummy_value_to_satisfy_openai_dependency"

[database]
host = "db.jnuhyxvvwpzasdszqrpe.supabase.co"
port = "5432"
dbname = "postgres"
user = "postgres"
password = "Hema!@#7254"
